### PR TITLE
feat: verify that TXs are in a validated ledger

### PR DESCRIPTION
**Pull request by dappelt**

### CODE REVIEW

**Review by sharafian — APPROVED** [review]

**Comment by intelliot** [comment]
Do you specify the `LastLedgerSequence` parameter on every transaction?

Do you handle the edge case where the transaction does not `tem`, but still never appears in a validated ledger?

**Comment by dappelt** [comment]
Thanks for your feedback @intelliot

This code does not explicitly set `LastLedgerSequence`. As I understand it, ripple-lib sets `LastLedgerSequence`. Is there any reason to set it manually?

> Do you handle the edge case where the transaction does not tem, but still never appears in a validated ledger?

How do you recommend handling such cases? From reading the [documentation](https://ripple.com/build/transactions/#lastledgersequence) I was under the impression that `LastLedgerSequence` would prevent such a scenario. Does ripple-lib emit the [transaction](https://github.com/interledgerjs/ilp-plugin-xrp-paychan-shared/pull/10/files#diff-fbe6ee078fc647377723c1d915edba0fR73) event in case a tx is past its `LastLedgerSequence`?

**Comment by intelliot** [comment]
Yes, ripple-lib sets `LastLedgerSequence` (aka `maxLedgerVersion`).

You should keep track of the `maxLedgerVersion` (from `tx.instructions.maxLedgerVersion`). Use [`getServerInfo`](https://ripple.com/build/rippleapi/#getserverinfo) and see if the `completeLedgers` range includes the ledger before you submitted the transaction and a ledger equal to or greater than the transaction's `maxLedgerVersion`. If so, use [`getTransaction`](https://ripple.com/build/rippleapi/#gettransaction) to see if the transaction was validated. If you get `MissingLedgerHistoryError`, then the transaction was not validated, and never will be.

More info: https://ripple.com/build/reliable-transaction-submission/

**Comment by intelliot** [comment]
No, I don't think that ripple-lib emits the transaction event when a tx is past its `LastLedgerSequence`. Subscribing to `accounts` doesn't tell rippled anything about the particular transaction you're interested in, so we only hear about transactions that appear in a validated ledger.

**Comment by dappelt** [comment]
I added some functionality to check if a pending tx is past its `maxLedgerVersion`.

@intelliot I would like to create an integration test for this functionality. Any recommendation how to make a local rippled return a `MissingLedgerHistoryError`?

**Comment by intelliot** [comment]
`MissingLedgerHistoryError` is actually a RippleAPI (ripple-lib) error, rather than a rippled one. That said, after looking into this further, I see that there's actually a better way to do this: by setting the `minLedgerVersion` and `maxLedgerVersion` options when calling `getTransaction`.

In this case, you'll actually get `PendingLedgerVersionError` until one of the following occurs:

1. The tx gets included in a validated ledger: you'll get the final result.
2. The latest validated ledger version exceeds `maxLedgerVersion`: you'll get `NotFoundError`.
3. rippled is missing one or more of the ledgers in the range `[minLedgerVersion-maxLedgerVersion]`: you'll get `MissingLedgerHistoryError`.

Case 1 is by far the most common. Case 2 is possible. Case 3 is very rare, but should be handled by:

1. Manually requesting the missing ledgers, or
2. Querying a different rippled server, and/or
3. Checking your account state (e.g. balances) in a validated ledger to see if the transaction was applied.

Here are the steps to follow when verifying txs in this way:

1. Before submitting the tx, get the current ledger version and use that as your `minLedgerVersion` option, e.g.
    `const {ledgerVersion: minLedgerVersion} = await api.getLedger()`
2. When polling `getTransaction`, specify the `minLedgerVersion` and `maxLedgerVersion` options.

Here's sample code for this: https://ripple.com/build/rippleapi-beginners-guide/#waiting-for-validation

Sorry for not finding this earlier!

**Comment by dappelt** [comment]
I modified the code to handle `MissingLedgerHistoryError` and `NotFoundError` (see `_verifyTx()`). I deviated slightly from your proposal by not polling for the transaction. Instead, I register an event handler on `ledgerClose` and retrieve the transaction once its `LastLedgerSequence` is reached. That saves some extra roundtrips to rippled.

**Review by intelliot — APPROVED** [review]
Great work!

My only concern would be, what happens if rippled disconnects or is restarted? I don’t think this is something we’ve tested elsewhere; it may be beyond the scope of this PR. I’ll try to look into this edge case next week.

**Comment by sharafian** [comment]
Yeah, I've actually noticed that my moneyd crashes fairly regularly with an unhandled error from RippleAPI. We should definitely make sure we're catching that

```
Error [ERR_UNHANDLED_ERROR]: Unhandled error. (websocket)
    at RippleAPI.emit (events.js:141:19)
    at RestrictedConnection.<anonymous> (/Users/sharafian/Documents/prog/moneyd/node_modules/ripple-lib/dist/npm/api.js:101:16)
    at RestrictedConnection.emit (events.js:160:13)
    at WebSocket.<anonymous> (/Users/sharafian/Documents/prog/moneyd/node_modules/ripple-lib/dist/npm/common/connection.js:225:18)
    at WebSocket.emit (events.js:160:13)
    at WebSocket.finalize (/Users/sharafian/Documents/prog/moneyd/node_modules/ws/lib/WebSocket.js:182:41)
    at TLSSocket.emit (events.js:160:13)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at process._tickCallback (internal/process/next_tick.js:152:19)
```

**Comment by dappelt** [comment]
We should register an error handler as described [here](https://github.com/ripple/ripple-lib/blob/develop/docs/index.md#error).

**Comment by intelliot** [comment]
Thinking about this a bit more - how reliable do we want transaction submission to be?

We probably want to handle the edge cases of a power outage or a network outage.

1. If we're concerned about the TxSubmitter losing power, then we need to write to a persistent data store and recover on restart.
2. When the network connection with rippled goes down, we should wait for connectivity to be restored, and then retry. Remember that it's safe to submit the same `signedTransaction` multiple times (assuming you are not re-signing) since the sequence number will be the same.

**Comment by mDuo13** [comment]
For the record, I took a look at this but my ability to grok JavaScript by reading it is poor enough that I don't have much of value to contribute. Sorry.

I do think you should consider edge cases like:

- I noticed s2.ripple.com was hardcoded in. What if s2.ripple.com is down or reports a ledger gap? (That's a full-history server that _shouldn't_ report a ledger gap, but maybe consider whether you're OK depending on public infrastructure not to fail you.) Also, that means you can't use the Test Net because s2 isn't on the Test Net. In fact, the Test Net doesn't have a full-history server at all.
- What if power goes out when you're submitting? Do you know what transactions you've submitted and what ranges to look for them in when you come back up? etc.

**Comment by dappelt** [comment]
Thanks for your feedback. Much appreciated.

I created an [issue](https://github.com/interledgerjs/ilp-plugin-xrp-paychan-shared/issues/14#issue-308985061) to further discuss transaction persistence in case of an unexpected shutdown.

Regarding a network outage, I can add retry logic for transaction submission. I also added an [issue](https://github.com/interledgerjs/ilp-plugin-xrp-paychan-shared/issues/13) for further discussion.

Good point on s2.ripple.com. I think it's ok that s2.ripple.com is hardcoded for now. It's only used as a failover in case the primary rippled is missing some of the recently closed ledgers. Note that we don't strictly need a full-history server. The ledger history needs to include only the ledgers from right before a transaction was submitted until the ledger signified by the transaction's `LastLedgerSequence` (approx. 3-4 ledgers).

Can you elaborate why we cannot use the testnet? I understand that s2 cannot serve as a failover for the test net. However, given that reliability is not a priority with test net transactions, I don't think we need a failover for the testnet at all.

**Comment by mDuo13** [comment]
Oh, I just meant that with s2 hard-coded, anything using the test net will fail extra hard if it gets to that. I didn't see that s2 was only used as a failover, which is better, although I think it would be best not to even try. (You don't want to accidentally submit to the main-net if your Test Net server goes down. Most likely, submitting a test-net transaction to the main net would fail due to things like LastLedgerSequence numbers being way smaller and accounts hopefully not being funded on both networks, but it's not a hard guarantee. You really should have a hard guarantee that a test-net fail won't lead to a main-net submission.)

**Comment by dappelt** [comment]
I think I created some confusion by writing that we use s2 as failover. Sorry about that. Let me be more precise. 

The [code](https://github.com/interledgerjs/ilp-plugin-xrp-paychan-shared/blob/master/lib/tx-submitter.js#L110-L138) uses s2 only to verify if a previously submitted transaction is included in a validated ledger and only in case the primary rippled instance is missing some of the recently closed ledgers. It will never submit transactions to s2. Transactions are always submitted to the primary rippled. Elliot outlined the procedure in this [comment](https://github.com/interledgerjs/ilp-plugin-xrp-paychan-shared/pull/10#issuecomment-375072250).

In consequence, a scenario where the code accidentally submits a test-net transactions to s2 is with the current code not possible. Anyway, good that you brought that point up. I will keep it in mind if we decide in the future to submit transactions to an alternative rippled.

**Pull request merged**
